name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  l10n_mapper_annotation: ^1.0.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  l10n_mapper_generator: ^1.0.0

flutter:
  uses-material-design: true
