name: example
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  l10n_mapper_annotation: 
    git:
      url: https://github.com/kwado-tech/l10n_mapper.git
      path: l10n_mapper_annotation
      ref: 1.2.10

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

  l10n_mapper_generator: 
    git:
      url: https://github.com/kwado-tech/l10n_mapper.git
      path: l10n_mapper_generator
      ref: 1.2.12

flutter:
  uses-material-design: true
