name: l10n_mapper_generator
description: A dart package to generate localization-mapper to support parsing
  dynamic translation keys (as flutter-localizations package does not yet
  support this).
version: 2.1.4
homepage: https://github.com/kwado-tech/l10n_mapper/tree/main/l10n_mapper_generator
repository: https://github.com/kwado-tech/l10n_mapper/tree/main/l10n_mapper_generator

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^7.1.0
  args: ^2.6.0
  build: ^2.4.2
  flutter:
    sdk: flutter
  path: ^1.9.0
  source_gen: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.14
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

executables:
  l10n_mapper_generator: l10n_mapper_generator
