name: l10n_mapper_generator
description: A dart package to generate localization-mapper to support parsing
  dynamic translation keys (as flutter-localizations package does not yet
  support this).
version: 2.3.0
homepage: https://github.com/kwado-tech/l10n_mapper/tree/main/l10n_mapper_generator
repository: https://github.com/kwado-tech/l10n_mapper/tree/main/l10n_mapper_generator

environment:
  sdk: ">=3.10.7 <4.0.0"
  flutter: ">=3.38.0"

dependencies:
  flutter:
    sdk: flutter
  analyzer: "8.3.0"
  args: ^2.7.0
  build: ">=3.0.0 <5.0.0"

  path: ^1.9.1
  source_gen: ">=3.1.0 <5.0.0"

dev_dependencies:
  build_runner: any
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

executables:
  l10n_mapper_generator: l10n_mapper_generator
