name: l10n_mapper_generator
description: A dart package to generate localization-mapper to support parsing
  dynamic translation keys (as flutter-localizations package does not yet
  support this).
version: 2.1.3
homepage: https://github.com/kwado-tech/l10n_mapper/tree/main/l10n_mapper_generator
repository: https://github.com/kwado-tech/l10n_mapper/tree/main/l10n_mapper_generator

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  analyzer: ^6.4.1
  args: ^2.4.2
  build: ^2.3.1
  flutter:
    sdk: flutter
  path: ^1.8.3
  source_gen: ^1.4.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter

executables:
  l10n_mapper_generator: l10n_mapper_generator

flutter: null
